resilience4j:
  circuitbreaker:
    instances:
      userService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000ms

spring:
  application:
    name: user-service-kafka2
  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
    config:
      uri: http://localhost:8888 # URL вашего Config Server
  kafka:
    bootstrap-servers: localhost:9092
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
